name:                ch06-lens
version:             0.1.0.0
github:              "binesiyu/ch06-lens"
license:             BSD3
author:              "yubin"
maintainer:          "1960028060@qq.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/binesiyu/ch06-lens#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- containers
- mtl
- hspec

library:
  source-dirs: src

executables:
  ch06-lens-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch06-lens

tests:
  ch06-lens-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch06-lens
